### ISSUE TITLE
NETFramework Version=v4.8 Error

### ISSUE THREAD

**Issue by SuperStark** [basicx-StrgV/WGet.NET#13]
Getting a "Could not install package 'WGet.NET 2.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

When trying to import the nuget package to a net framework 4.8 project

Anygot got a quick fix?

**Comment by basicx-StrgV** [comment]
Hi,
your project targets the __.NET Framework 4.8__, which is not supported by this library.
The library is written in __.NET Core 3.1__ and therefore only supports the same or higher versions. 
If there is no specific reason as to why you used .NET Framework 4.8 for your project, I would recommend using at least .NET 6.0 (Oldest LTS version) for new applications*.

__If you need to use .NET Framework 4.8 for your project, the library can not be used with it.__

**I don’t know how familiar you are with .NET, but if you are quite new to it, you should make yourself familiar with the different .NET versions.  
The different names and versions can be a little confusing at first. I would recommend to read the following article, that gives a simple explanation about the different versions: https://learn.microsoft.com/en-us/ef/core/miscellaneous/platforms*

**Comment by SuperStark** [comment]
> Hi, your project targets the **.NET Framework 4.8**, which is not supported by this library. The library is written in **.NET Core 3.1** and therefore only supports the same or higher versions. If there is no specific reason as to why you used .NET Framework 4.8 for your project, I would recommend using at least .NET 6.0 (Oldest LTS version) for new applications*.
> 
> **If you need to use .NET Framework 4.8 for your project, the library can not be used with it.**
> 
> *_I don’t know how familiar you are with .NET, but if you are quite new to it, you should make yourself familiar with the different .NET versions. The different names and versions can be a little confusing at first. I would recommend to read the following article, that gives a simple explanation about the different versions: https://learn.microsoft.com/en-us/ef/core/miscellaneous/platforms_

Thank you for the response, unfortunately the project I have is too big to convert to .net core (without breaking a lot of things!)
I think I will write a CLI using .net core and incorporate WGet.NET to get correctly formatted results.

My issue is related to extracting strings from Winget eg just Name and ID and adding them to separate list boxes, but as the ID can contain multiple sizes and full stops its rather hard to code a substring - your tool looks like the answer.

**Comment by basicx-StrgV** [comment]
You could also try the following option, if it is viable for your project.  

The library is under the MIT license, so you can use any part of the code if you provide the original license with it.  
If your application only needs to get the name and id of a package, and it already has the winget output, you might be interested in just using the static ‘ProcessOutputReader’ class from the library.  
https://github.com/basicx-StrgV/WGet.NET/blob/main/src/WGet.NET/HelperClasses/ProcessOutputReader.cs  

You could copy it and port it to your target framework version.  
The class is not that big and all source related content can properly be removed for your use case.  

The `ToPackageList` method of the class, takes the winget output as a string array containing the output lines, an enum providing information about the actions, and a source name.  
You properly can ignore the source name input, because it is only used to provide the source info to the packages, if the output is filtered by source.  

``` csharp
public static List<WinGetPackage> ToPackageList(string[] output, PackageAction action = PackageAction.Default, string? sourceName = null)
```

It will return a list of `WinGetPackage` objects containing the info that you need.

**Comment by basicx-StrgV** [comment]
Seeing that this seems to be a bigger problem than I first thought, because I did not expect people to use the library in older software, I will think about a solution to support older framework versions.

Please refer to the following Issue for further updates.
#15
